### ISSUE TITLE
Define model

### ISSUE THREAD

**Issue by christopherkane** [zeroish/qwiz#9]

**Comment by christopherkane** [comment]
Assumptions
- A room can have many contestants.
- A room can have many questions.
- A question can appear in many rooms.

As such, I have come up with the following ER diagram.
![image](https://user-images.githubusercontent.com/4212311/31865677-7e9b67f0-b76a-11e7-99b0-a63af3877bc5.png)

@zeroish, can you take a look at this?

**Comment by zeroish** [comment]
Tags should be split out as their own entity. Therefore given a:

* Question can have multiple Tags
* Tag can have multiple Questions

We'll need a join table for QuestionTags also.

**Comment by christopherkane** [comment]
Perfect! Thanks for the input.
![image](https://user-images.githubusercontent.com/4212311/32066262-1fa24f88-ba77-11e7-85f4-d17643a73634.png)

**Comment by christopherkane** [comment]
Is there a better way to store the three incorrect answers? Or are three fields the best way?

**Comment by christopherkane** [comment]
Right, here is the new and improved ER diagram.
![qwiz_er_diagram](https://user-images.githubusercontent.com/4212311/32296845-444737e0-bf45-11e7-8642-92915979b1e4.png)
I will update the Models to reflect this Entity Relationship diagram, using the ManyToManyField relationship field provided by Django to create the intermediary join tables.
Any missing fields guys? @zeroish @pgcrooks
